### ISSUE TITLE
"tozero = T" has no effect for some TypeIII curves

### ISSUE THREAD

**Issue by dpritchard** [dpritchard/frair#17]
Many (all?) type III curves are undefined when x = 0. Therefore there is no (visible) effect of the following:

`lines(tII_model, ..., tozero = TRUE)`
`drawpoly(tII_boot, ..., tozero = TRUE)`

This might lead some users to think that FRAIR is "broken"...

Possible solutions:
1) Return the results invisibly so users can inspect the output more easily. 
2) Remove the "tozero" argument (Back to the original "zero has no meaning" rationale!)
3) Throw a warning if zero is undefined?
4) Plot in smaller steps e.g. `seq(from = 0, to = max(x), by = 0.001)`
5) Plot integers, but replace zero with very small positive number instead of zero (0.00000001)

The solution will likely be a combination of the above?

This issue stems from #10.

**Comment by DBarriosONeill** [comment]
#5 would work for plotting, but is a bit of a hack. ifelse() to deal with NaNs and allow the quantiles to still be predicted as more and more of them become too small to make a non zero prediction.
